# Generated by Django 3.1.5 on 2022-04-12 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoPeso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text='Use dd/mm/aaaa', verbose_name='Data de atualização de peso *')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso atual (Kg) *')),
                ('imc', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Índice de Massa Corporal (calculado)')),
                ('tmb', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Taxa Metabolismo Basal (calculado)')),
                ('percentual_gordura', models.DecimalField(blank=True, decimal_places=0, help_text='Número inteiro (sem casas decimais)', max_digits=3, null=True, verbose_name='Percentual de gordura (%)')),
                ('is_active', models.BooleanField(default=False, help_text='Se ativo, o usuário tem permissão para acessar o sistema', verbose_name='Ativo')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Hash')),
                ('cliente', models.ForeignKey(help_text='* indica campo obrigatório.', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Cliente *')),
            ],
            options={
                'ordering': ['cliente', '-data'],
            },
        ),
    ]
