# Generated by Django 3.1.5 on 2022-04-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico_peso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicopeso',
            name='imc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Índice de Massa Corporal (calculado)'),
        ),
        migrations.AlterField(
            model_name='historicopeso',
            name='tmb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Taxa Metabolismo Basal (calculado)'),
        ),
    ]
