# Generated by Django 3.1.5 on 2021-11-03 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_atividade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroatividade',
            name='esforco',
            field=models.CharField(choices=[('7 - MUITO FÁCIL', '7 - Muito fácil'), ('9 - FÁCIL', '9 - Fácil'), ('11 - RELATIVAMENTE FÁCIL', '11 - Relativamente fácil'), ('13 - LIGEIRAMENTE CANSATIVO', '13 - Ligeiramente cansativo'), ('15 - CANSATIVO', '15 - Cansativo'), ('17 - MUITO CANSATIVO', '17 - Muito cansativo'), ('19 - EXAUSTIVO', '19 - Exaustivo')], help_text='Em relação ao esforço na atividade', max_length=27, verbose_name='Esforço subjetivo *'),
        ),
        migrations.AlterField(
            model_name='registroatividade',
            name='frequencia_cardiaca_media',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Caso tenha utilizado um frequêncímetro durante a atividade', max_digits=3, null=True, verbose_name='Frequência cardíaca média durante a atividade'),
        ),
    ]
