# Generated by Django 3.1.5 on 2022-04-05 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registro_atividade', '0002_auto_20211103_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroatividade',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='* indica campo obrigatório.', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
