# Generated by Django 3.1.5 on 2022-04-05 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registro_atividade', '0003_registroatividade_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroatividade',
            name='cliente',
            field=models.ForeignKey(help_text='* indica campo obrigatório.', on_delete=django.db.models.deletion.PROTECT, to='usuario.usuario', verbose_name='Usuario *'),
        ),
    ]
