# Generated by Django 3.1.5 on 2021-09-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Altura (metros) *'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='data_nascimento',
            field=models.DateField(blank=True, help_text='dd/mm/aaaa', null=True, verbose_name='Data de nascimento *'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='imc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Índice de Massa Corporal (calculado)'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='percentual_gordura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Percentual de gordura (%)'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (Kg) *'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(blank=True, choices=[('MASCULINO', 'Masculino'), ('FEMININO', 'Feminino')], help_text='Campo obrigatório para cálculo de gasto energético/calórico e consumo alimentar', max_length=10, null=True, verbose_name='Sexo *'),
        ),
    ]
