# Generated by Django 3.1.5 on 2021-09-22 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20210922_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='percentual_gordura',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Número inteiro (sem casas decimais)', max_digits=3, null=True, verbose_name='Percentual de gordura (%)'),
        ),
    ]
