# Generated by Django 3.1.5 on 2022-04-19 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20210922_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='imc',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='percentual_gordura',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='peso',
        ),
    ]
