# Generated by Django 3.1.5 on 2021-09-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(help_text='Seja sucinto na descrição do alimento. Lembre que é campo obrigatório', max_length=1000, verbose_name='Descrição do alimento *')),
                ('unidade', models.TextField(help_text='ml ou colher ou fatia ou porção, etc', max_length=100, verbose_name='Unidade do alimento *')),
                ('calorias', models.DecimalField(decimal_places=0, help_text='Quantidade de calorias para a unidade definida desse alimento', max_digits=5, verbose_name='Quantidade de calorias da unidade desse alimento *')),
                ('carboidratos', models.DecimalField(decimal_places=0, help_text='Quantidade de calorias para a unidade definida desse alimento', max_digits=5, verbose_name='Quantidade de calorias da unidade desse alimento *')),
                ('fonte', models.TextField(blank=True, help_text='Use como referência alguma instituição ou trabalho', max_length=1000, null=True, verbose_name='Fonte ou referência desse alimento')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Hash')),
            ],
            options={
                'verbose_name': 'alimento',
                'verbose_name_plural': 'alimentos',
                'ordering': ['descricao'],
            },
        ),
    ]
