# Generated by Django 3.1.5 on 2021-09-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='calorias',
            field=models.DecimalField(decimal_places=0, help_text='Quantidade de calorias para a unidade definida desse alimento', max_digits=5, verbose_name='Quantidade de calorias (g) da unidade desse alimento *'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='carboidratos',
            field=models.DecimalField(decimal_places=0, help_text='Quantidade de calorias para a unidade definida desse alimento', max_digits=5, verbose_name='Quantidade de carboidratos (g) da unidade desse alimento *'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='descricao',
            field=models.CharField(help_text='Seja sucinto na descrição do alimento. Lembre que é campo obrigatório', max_length=1000, verbose_name='Descrição do alimento *'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='unidade',
            field=models.CharField(help_text='ml ou colher ou fatia ou porção, etc', max_length=100, verbose_name='Unidade do alimento *'),
        ),
    ]
