# Generated by Django 3.1.5 on 2021-10-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_refeicao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrorefeicao',
            name='total_calorias',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrorefeicao',
            name='total_carboidratos',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
            preserve_default=False,
        ),
    ]
