# Generated by Django 3.1.5 on 2021-11-03 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_refeicao', '0002_auto_20211027_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrorefeicao',
            name='total_calorias',
            field=models.DecimalField(decimal_places=1, max_digits=6),
        ),
        migrations.AlterField(
            model_name='registrorefeicao',
            name='total_carboidratos',
            field=models.DecimalField(decimal_places=1, max_digits=6),
        ),
    ]
