# Generated by Django 3.1.5 on 2022-03-24 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registro_refeicao', '0003_auto_20211103_1915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrorefeicao',
            options={'ordering': ['cliente', 'data', 'hora', 'alimento'], 'verbose_name': 'registro_refeicao', 'verbose_name_plural': 'registros_refeicoes'},
        ),
        migrations.AddField(
            model_name='registrorefeicao',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='* indica campo obrigatório.', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
